// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runtime_node_proto.proto

package com.ansross.accessibilityplugin.nodeProto;

public final class RuntimeNodeProtos {
  private RuntimeNodeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LabelNodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:runtimeNodeProto.LabelNode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string resourceId = 1;</code>
     * @return Whether the resourceId field is set.
     */
    boolean hasResourceId();
    /**
     * <code>optional string resourceId = 1;</code>
     * @return The resourceId.
     */
    java.lang.String getResourceId();
    /**
     * <code>optional string resourceId = 1;</code>
     * @return The bytes for resourceId.
     */
    com.google.protobuf.ByteString
        getResourceIdBytes();

    /**
     * <code>optional string label = 2;</code>
     * @return Whether the label field is set.
     */
    boolean hasLabel();
    /**
     * <code>optional string label = 2;</code>
     * @return The label.
     */
    java.lang.String getLabel();
    /**
     * <code>optional string label = 2;</code>
     * @return The bytes for label.
     */
    com.google.protobuf.ByteString
        getLabelBytes();

    /**
     * <code>optional .runtimeNodeProto.LabelNode.AttributeType attribute = 3;</code>
     * @return Whether the attribute field is set.
     */
    boolean hasAttribute();
    /**
     * <code>optional .runtimeNodeProto.LabelNode.AttributeType attribute = 3;</code>
     * @return The attribute.
     */
    com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.AttributeType getAttribute();

    /**
     * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
     */
    java.util.List<com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode> 
        getContributingNodesList();
    /**
     * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
     */
    com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode getContributingNodes(int index);
    /**
     * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
     */
    int getContributingNodesCount();
    /**
     * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
     */
    java.util.List<? extends com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNodeOrBuilder> 
        getContributingNodesOrBuilderList();
    /**
     * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
     */
    com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNodeOrBuilder getContributingNodesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code runtimeNodeProto.LabelNode}
   */
  public static final class LabelNode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:runtimeNodeProto.LabelNode)
      LabelNodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LabelNode.newBuilder() to construct.
    private LabelNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LabelNode() {
      resourceId_ = "";
      label_ = "";
      attribute_ = 0;
      contributingNodes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LabelNode();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LabelNode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              resourceId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              label_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.AttributeType value = com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.AttributeType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                attribute_ = rawValue;
              }
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                contributingNodes_ = new java.util.ArrayList<com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode>();
                mutable_bitField0_ |= 0x00000008;
              }
              contributingNodes_.add(
                  input.readMessage(com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          contributingNodes_ = java.util.Collections.unmodifiableList(contributingNodes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.internal_static_runtimeNodeProto_LabelNode_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.internal_static_runtimeNodeProto_LabelNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.class, com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.Builder.class);
    }

    /**
     * Protobuf enum {@code runtimeNodeProto.LabelNode.AttributeType}
     */
    public enum AttributeType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TEXT = 0;</code>
       */
      TEXT(0),
      /**
       * <code>CONTENTDESC = 1;</code>
       */
      CONTENTDESC(1),
      /**
       * <code>HINT = 2;</code>
       */
      HINT(2),
      /**
       * <code>LABELFOR = 3;</code>
       */
      LABELFOR(3),
      ;

      /**
       * <code>TEXT = 0;</code>
       */
      public static final int TEXT_VALUE = 0;
      /**
       * <code>CONTENTDESC = 1;</code>
       */
      public static final int CONTENTDESC_VALUE = 1;
      /**
       * <code>HINT = 2;</code>
       */
      public static final int HINT_VALUE = 2;
      /**
       * <code>LABELFOR = 3;</code>
       */
      public static final int LABELFOR_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static AttributeType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static AttributeType forNumber(int value) {
        switch (value) {
          case 0: return TEXT;
          case 1: return CONTENTDESC;
          case 2: return HINT;
          case 3: return LABELFOR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<AttributeType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          AttributeType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<AttributeType>() {
              public AttributeType findValueByNumber(int number) {
                return AttributeType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.getDescriptor().getEnumTypes().get(0);
      }

      private static final AttributeType[] VALUES = values();

      public static AttributeType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private AttributeType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:runtimeNodeProto.LabelNode.AttributeType)
    }

    private int bitField0_;
    public static final int RESOURCEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object resourceId_;
    /**
     * <code>optional string resourceId = 1;</code>
     * @return Whether the resourceId field is set.
     */
    @java.lang.Override
    public boolean hasResourceId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string resourceId = 1;</code>
     * @return The resourceId.
     */
    @java.lang.Override
    public java.lang.String getResourceId() {
      java.lang.Object ref = resourceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resourceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string resourceId = 1;</code>
     * @return The bytes for resourceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResourceIdBytes() {
      java.lang.Object ref = resourceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resourceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LABEL_FIELD_NUMBER = 2;
    private volatile java.lang.Object label_;
    /**
     * <code>optional string label = 2;</code>
     * @return Whether the label field is set.
     */
    @java.lang.Override
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string label = 2;</code>
     * @return The label.
     */
    @java.lang.Override
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          label_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string label = 2;</code>
     * @return The bytes for label.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATTRIBUTE_FIELD_NUMBER = 3;
    private int attribute_;
    /**
     * <code>optional .runtimeNodeProto.LabelNode.AttributeType attribute = 3;</code>
     * @return Whether the attribute field is set.
     */
    @java.lang.Override public boolean hasAttribute() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .runtimeNodeProto.LabelNode.AttributeType attribute = 3;</code>
     * @return The attribute.
     */
    @java.lang.Override public com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.AttributeType getAttribute() {
      @SuppressWarnings("deprecation")
      com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.AttributeType result = com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.AttributeType.valueOf(attribute_);
      return result == null ? com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.AttributeType.TEXT : result;
    }

    public static final int CONTRIBUTINGNODES_FIELD_NUMBER = 4;
    private java.util.List<com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode> contributingNodes_;
    /**
     * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
     */
    @java.lang.Override
    public java.util.List<com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode> getContributingNodesList() {
      return contributingNodes_;
    }
    /**
     * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNodeOrBuilder> 
        getContributingNodesOrBuilderList() {
      return contributingNodes_;
    }
    /**
     * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
     */
    @java.lang.Override
    public int getContributingNodesCount() {
      return contributingNodes_.size();
    }
    /**
     * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
     */
    @java.lang.Override
    public com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode getContributingNodes(int index) {
      return contributingNodes_.get(index);
    }
    /**
     * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
     */
    @java.lang.Override
    public com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNodeOrBuilder getContributingNodesOrBuilder(
        int index) {
      return contributingNodes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, resourceId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, label_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(3, attribute_);
      }
      for (int i = 0; i < contributingNodes_.size(); i++) {
        output.writeMessage(4, contributingNodes_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, resourceId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, label_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, attribute_);
      }
      for (int i = 0; i < contributingNodes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, contributingNodes_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode)) {
        return super.equals(obj);
      }
      com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode other = (com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode) obj;

      if (hasResourceId() != other.hasResourceId()) return false;
      if (hasResourceId()) {
        if (!getResourceId()
            .equals(other.getResourceId())) return false;
      }
      if (hasLabel() != other.hasLabel()) return false;
      if (hasLabel()) {
        if (!getLabel()
            .equals(other.getLabel())) return false;
      }
      if (hasAttribute() != other.hasAttribute()) return false;
      if (hasAttribute()) {
        if (attribute_ != other.attribute_) return false;
      }
      if (!getContributingNodesList()
          .equals(other.getContributingNodesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResourceId()) {
        hash = (37 * hash) + RESOURCEID_FIELD_NUMBER;
        hash = (53 * hash) + getResourceId().hashCode();
      }
      if (hasLabel()) {
        hash = (37 * hash) + LABEL_FIELD_NUMBER;
        hash = (53 * hash) + getLabel().hashCode();
      }
      if (hasAttribute()) {
        hash = (37 * hash) + ATTRIBUTE_FIELD_NUMBER;
        hash = (53 * hash) + attribute_;
      }
      if (getContributingNodesCount() > 0) {
        hash = (37 * hash) + CONTRIBUTINGNODES_FIELD_NUMBER;
        hash = (53 * hash) + getContributingNodesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code runtimeNodeProto.LabelNode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:runtimeNodeProto.LabelNode)
        com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.internal_static_runtimeNodeProto_LabelNode_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.internal_static_runtimeNodeProto_LabelNode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.class, com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.Builder.class);
      }

      // Construct using com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getContributingNodesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        resourceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        label_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        attribute_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (contributingNodesBuilder_ == null) {
          contributingNodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          contributingNodesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.internal_static_runtimeNodeProto_LabelNode_descriptor;
      }

      @java.lang.Override
      public com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode getDefaultInstanceForType() {
        return com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.getDefaultInstance();
      }

      @java.lang.Override
      public com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode build() {
        com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode buildPartial() {
        com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode result = new com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resourceId_ = resourceId_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.label_ = label_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.attribute_ = attribute_;
        if (contributingNodesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            contributingNodes_ = java.util.Collections.unmodifiableList(contributingNodes_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.contributingNodes_ = contributingNodes_;
        } else {
          result.contributingNodes_ = contributingNodesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode) {
          return mergeFrom((com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode other) {
        if (other == com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.getDefaultInstance()) return this;
        if (other.hasResourceId()) {
          bitField0_ |= 0x00000001;
          resourceId_ = other.resourceId_;
          onChanged();
        }
        if (other.hasLabel()) {
          bitField0_ |= 0x00000002;
          label_ = other.label_;
          onChanged();
        }
        if (other.hasAttribute()) {
          setAttribute(other.getAttribute());
        }
        if (contributingNodesBuilder_ == null) {
          if (!other.contributingNodes_.isEmpty()) {
            if (contributingNodes_.isEmpty()) {
              contributingNodes_ = other.contributingNodes_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureContributingNodesIsMutable();
              contributingNodes_.addAll(other.contributingNodes_);
            }
            onChanged();
          }
        } else {
          if (!other.contributingNodes_.isEmpty()) {
            if (contributingNodesBuilder_.isEmpty()) {
              contributingNodesBuilder_.dispose();
              contributingNodesBuilder_ = null;
              contributingNodes_ = other.contributingNodes_;
              bitField0_ = (bitField0_ & ~0x00000008);
              contributingNodesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getContributingNodesFieldBuilder() : null;
            } else {
              contributingNodesBuilder_.addAllMessages(other.contributingNodes_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object resourceId_ = "";
      /**
       * <code>optional string resourceId = 1;</code>
       * @return Whether the resourceId field is set.
       */
      public boolean hasResourceId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string resourceId = 1;</code>
       * @return The resourceId.
       */
      public java.lang.String getResourceId() {
        java.lang.Object ref = resourceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            resourceId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string resourceId = 1;</code>
       * @return The bytes for resourceId.
       */
      public com.google.protobuf.ByteString
          getResourceIdBytes() {
        java.lang.Object ref = resourceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resourceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string resourceId = 1;</code>
       * @param value The resourceId to set.
       * @return This builder for chaining.
       */
      public Builder setResourceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        resourceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string resourceId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResourceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resourceId_ = getDefaultInstance().getResourceId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string resourceId = 1;</code>
       * @param value The bytes for resourceId to set.
       * @return This builder for chaining.
       */
      public Builder setResourceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        resourceId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object label_ = "";
      /**
       * <code>optional string label = 2;</code>
       * @return Whether the label field is set.
       */
      public boolean hasLabel() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string label = 2;</code>
       * @return The label.
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            label_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string label = 2;</code>
       * @return The bytes for label.
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string label = 2;</code>
       * @param value The label to set.
       * @return This builder for chaining.
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLabel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 2;</code>
       * @param value The bytes for label to set.
       * @return This builder for chaining.
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        label_ = value;
        onChanged();
        return this;
      }

      private int attribute_ = 0;
      /**
       * <code>optional .runtimeNodeProto.LabelNode.AttributeType attribute = 3;</code>
       * @return Whether the attribute field is set.
       */
      @java.lang.Override public boolean hasAttribute() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .runtimeNodeProto.LabelNode.AttributeType attribute = 3;</code>
       * @return The attribute.
       */
      @java.lang.Override
      public com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.AttributeType getAttribute() {
        @SuppressWarnings("deprecation")
        com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.AttributeType result = com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.AttributeType.valueOf(attribute_);
        return result == null ? com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.AttributeType.TEXT : result;
      }
      /**
       * <code>optional .runtimeNodeProto.LabelNode.AttributeType attribute = 3;</code>
       * @param value The attribute to set.
       * @return This builder for chaining.
       */
      public Builder setAttribute(com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.AttributeType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        attribute_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .runtimeNodeProto.LabelNode.AttributeType attribute = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttribute() {
        bitField0_ = (bitField0_ & ~0x00000004);
        attribute_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode> contributingNodes_ =
        java.util.Collections.emptyList();
      private void ensureContributingNodesIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          contributingNodes_ = new java.util.ArrayList<com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode>(contributingNodes_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode, com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.Builder, com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNodeOrBuilder> contributingNodesBuilder_;

      /**
       * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
       */
      public java.util.List<com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode> getContributingNodesList() {
        if (contributingNodesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(contributingNodes_);
        } else {
          return contributingNodesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
       */
      public int getContributingNodesCount() {
        if (contributingNodesBuilder_ == null) {
          return contributingNodes_.size();
        } else {
          return contributingNodesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
       */
      public com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode getContributingNodes(int index) {
        if (contributingNodesBuilder_ == null) {
          return contributingNodes_.get(index);
        } else {
          return contributingNodesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
       */
      public Builder setContributingNodes(
          int index, com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode value) {
        if (contributingNodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContributingNodesIsMutable();
          contributingNodes_.set(index, value);
          onChanged();
        } else {
          contributingNodesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
       */
      public Builder setContributingNodes(
          int index, com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.Builder builderForValue) {
        if (contributingNodesBuilder_ == null) {
          ensureContributingNodesIsMutable();
          contributingNodes_.set(index, builderForValue.build());
          onChanged();
        } else {
          contributingNodesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
       */
      public Builder addContributingNodes(com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode value) {
        if (contributingNodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContributingNodesIsMutable();
          contributingNodes_.add(value);
          onChanged();
        } else {
          contributingNodesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
       */
      public Builder addContributingNodes(
          int index, com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode value) {
        if (contributingNodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContributingNodesIsMutable();
          contributingNodes_.add(index, value);
          onChanged();
        } else {
          contributingNodesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
       */
      public Builder addContributingNodes(
          com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.Builder builderForValue) {
        if (contributingNodesBuilder_ == null) {
          ensureContributingNodesIsMutable();
          contributingNodes_.add(builderForValue.build());
          onChanged();
        } else {
          contributingNodesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
       */
      public Builder addContributingNodes(
          int index, com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.Builder builderForValue) {
        if (contributingNodesBuilder_ == null) {
          ensureContributingNodesIsMutable();
          contributingNodes_.add(index, builderForValue.build());
          onChanged();
        } else {
          contributingNodesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
       */
      public Builder addAllContributingNodes(
          java.lang.Iterable<? extends com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode> values) {
        if (contributingNodesBuilder_ == null) {
          ensureContributingNodesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, contributingNodes_);
          onChanged();
        } else {
          contributingNodesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
       */
      public Builder clearContributingNodes() {
        if (contributingNodesBuilder_ == null) {
          contributingNodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          contributingNodesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
       */
      public Builder removeContributingNodes(int index) {
        if (contributingNodesBuilder_ == null) {
          ensureContributingNodesIsMutable();
          contributingNodes_.remove(index);
          onChanged();
        } else {
          contributingNodesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
       */
      public com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.Builder getContributingNodesBuilder(
          int index) {
        return getContributingNodesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
       */
      public com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNodeOrBuilder getContributingNodesOrBuilder(
          int index) {
        if (contributingNodesBuilder_ == null) {
          return contributingNodes_.get(index);  } else {
          return contributingNodesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
       */
      public java.util.List<? extends com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNodeOrBuilder> 
           getContributingNodesOrBuilderList() {
        if (contributingNodesBuilder_ != null) {
          return contributingNodesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(contributingNodes_);
        }
      }
      /**
       * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
       */
      public com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.Builder addContributingNodesBuilder() {
        return getContributingNodesFieldBuilder().addBuilder(
            com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.getDefaultInstance());
      }
      /**
       * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
       */
      public com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.Builder addContributingNodesBuilder(
          int index) {
        return getContributingNodesFieldBuilder().addBuilder(
            index, com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.getDefaultInstance());
      }
      /**
       * <code>repeated .runtimeNodeProto.LabelNode contributingNodes = 4;</code>
       */
      public java.util.List<com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.Builder> 
           getContributingNodesBuilderList() {
        return getContributingNodesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode, com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.Builder, com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNodeOrBuilder> 
          getContributingNodesFieldBuilder() {
        if (contributingNodesBuilder_ == null) {
          contributingNodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode, com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode.Builder, com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNodeOrBuilder>(
                  contributingNodes_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          contributingNodes_ = null;
        }
        return contributingNodesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:runtimeNodeProto.LabelNode)
    }

    // @@protoc_insertion_point(class_scope:runtimeNodeProto.LabelNode)
    private static final com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode();
    }

    public static com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<LabelNode>
        PARSER = new com.google.protobuf.AbstractParser<LabelNode>() {
      @java.lang.Override
      public LabelNode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LabelNode(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LabelNode> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LabelNode> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ansross.accessibilityplugin.nodeProto.RuntimeNodeProtos.LabelNode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_runtimeNodeProto_LabelNode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_runtimeNodeProto_LabelNode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030runtime_node_proto.proto\022\020runtimeNodeP" +
      "roto\"\350\001\n\tLabelNode\022\022\n\nresourceId\030\001 \001(\t\022\r" +
      "\n\005label\030\002 \001(\t\022<\n\tattribute\030\003 \001(\0162).runti" +
      "meNodeProto.LabelNode.AttributeType\0226\n\021c" +
      "ontributingNodes\030\004 \003(\0132\033.runtimeNodeProt" +
      "o.LabelNode\"B\n\rAttributeType\022\010\n\004TEXT\020\000\022\017" +
      "\n\013CONTENTDESC\020\001\022\010\n\004HINT\020\002\022\014\n\010LABELFOR\020\003B" +
      ">\n)com.ansross.accessibilityplugin.nodeP" +
      "rotoB\021RuntimeNodeProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_runtimeNodeProto_LabelNode_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_runtimeNodeProto_LabelNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_runtimeNodeProto_LabelNode_descriptor,
        new java.lang.String[] { "ResourceId", "Label", "Attribute", "ContributingNodes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
